POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "video nod",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/9b530fa0-74bf-4d70-baab-12d88d1c4c71
Content-Type: application/json


{
  "title": "video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}


###

DELETE http://localhost:3333/videos/9b530fa0-74bf-4d70-baab-12d88d1c4c71