POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "video 01",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/9858407c-29a8-42b8-a90b-269a5dddc51c
Content-Type: application/json


{
  "title": "video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}


###

DELETE http://localhost:3333/videos/89e2c03c-d52b-4222-b8cc-48fdc6c9fde3